name: Mirror main -> public HierVision

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo @ main (with LFS)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          lfs: true                # <-- pull LFS pointers + blobs
          persist-credentials: false

      - name: Ensure LFS files are present
        run: |
          git lfs install
          # Fetch ALL LFS objects referenced by current refs, then materialize them
          git lfs fetch --all
          git lfs checkout

      - name: Configure Git identity
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Push ONLY main to public repo
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euxo pipefail
          SRC_BRANCH="main"
          DEST_BRANCH="main"
          TARGET_OWNER="tkasarla"
          TARGET_REPO="HierVision"
          TARGET_URL="https://${MIRROR_TOKEN}@github.com/${TARGET_OWNER}/${TARGET_REPO}.git"

          git remote add publish "$TARGET_URL"

          # Optional: push LFS objects proactively (then the ref)
          git lfs push publish --all || true

          # Push exactly the branch; --force keeps mirror exact
          git push publish "refs/heads/${SRC_BRANCH}:refs/heads/${DEST_BRANCH}" --force