name: Mirror main -> public HierVision (strip workflows, preserve contributors)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo @ main (full history + LFS)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          lfs: true
          persist-credentials: false

      - name: Install & hydrate LFS
        run: |
          git lfs install
          git lfs fetch --all
          git lfs checkout

      - name: Install git-filter-repo
        run: |
          python -m pip install --upgrade pip
          python -m pip install git-filter-repo

      - name: Remove .github/workflows from entire history (authors preserved)
        run: |
          # This rewrites the current repository in-place,
          # deleting the .github/workflows path from ALL commits.
          git filter-repo --path .github/workflows --invert-paths --force

      - name: Configure Git identity
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Push to public repo (PAT)
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euxo pipefail
          TARGET_OWNER="tkasarla"
          TARGET_REPO="HierVision"
          TARGET_URL="https://${MIRROR_TOKEN}@github.com/${TARGET_OWNER}/${TARGET_REPO}.git"

          git remote remove origin || true
          git remote add publish "$TARGET_URL"

          # Push LFS objects first (optional)
          git lfs push publish --all || true

          # Force-push rewritten main; includes full (cleaned) history so contributors show
          git push publish "HEAD:refs/heads/main" --force