name: Mirror main -> public HierVision (no workflows)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo @ main with LFS
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          lfs: true
          persist-credentials: false

      - name: Prepare publish tree (exclude workflows)
        run: |
          set -euxo pipefail
          rm -rf publish
          mkdir -p publish
          # copy everything except the workflows directory
          rsync -a --delete --exclude='.git' --exclude='.github/workflows' ./ publish/

      - name: Rebuild repo for publishing (fresh history)
        working-directory: publish
        run: |
          set -euxo pipefail
          git init
          git checkout -b main
          git lfs install
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          git add -A
          git commit -m "Mirror from HierVision_private @ $GITHUB_SHA"

      - name: Push to public repo
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        working-directory: publish
        run: |
          set -euxo pipefail
          TARGET_OWNER="tkasarla"
          TARGET_REPO="HierVision"
          TARGET_URL="https://${MIRROR_TOKEN}@github.com/${TARGET_OWNER}/${TARGET_REPO}.git"

          git remote add publish "$TARGET_URL"
          # optional: push LFS first, then the ref
          git lfs push publish --all || true
          git push publish "refs/heads/main:refs/heads/main" --force