name: Sync private to public

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
  workflow_dispatch:
    inputs:
      force:
        description: "Force push to public"
        required: false
        default: "false"

jobs:
  sync_to_public:
    # Don't run if this push came from pull-from-public workflow
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[sync-from-public]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          lfs: false

      - name: Configure SSH
        run: |
          set -euo pipefail

          if [ -z "${{ secrets.PUBLIC_DEPLOY_KEY_B64 }}" ]; then
            echo "::error::PUBLIC_DEPLOY_KEY_B64 secret is empty"
            exit 1
          fi

          install -m 700 -d ~/.ssh
          printf '%s' "${{ secrets.PUBLIC_DEPLOY_KEY_B64 }}" | base64 --decode > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Verify SSH works (ssh exits with 1 on success for GitHub, so capture output)
          AUTH_OUTPUT=$(ssh -T git@github.com 2>&1 || true)
          echo "$AUTH_OUTPUT"
          if ! printf '%s' "$AUTH_OUTPUT" | grep -q "successfully authenticated"; then
            echo "::error::SSH authentication failed — confirm deploy key has write access"
            exit 1
          fi
          echo "SSH authentication successful"

      - name: Configure Git
        run: |
          set -euo pipefail
          git config user.name "sync-bot"
          git config user.email "sync-bot@users.noreply.github.com"

      - name: Setup remote and create branch without workflows
        run: |
          set -euo pipefail
          git remote add public git@github.com:tkasarla/HierVision.git || true
          git remote set-url public git@github.com:tkasarla/HierVision.git
          git fetch public main || echo "Public main doesn't exist yet"
          
          git checkout -b temp-public-sync
          
          if [ -d .github/workflows ]; then
            echo "Removing .github/workflows directory"
            git rm -rf .github/workflows
            if ! git diff --cached --quiet; then
              ORIG_AUTHOR_NAME=$(git show -s --format='%an' HEAD)
              ORIG_AUTHOR_EMAIL=$(git show -s --format='%ae' HEAD)
              ORIG_AUTHOR_DATE=$(git show -s --format='%aI' HEAD)
              ORIG_COMMITTER_NAME=$(git show -s --format='%cn' HEAD)
              ORIG_COMMITTER_EMAIL=$(git show -s --format='%ce' HEAD)
              ORIG_COMMITTER_DATE=$(git show -s --format='%cI' HEAD)

              echo "Amending commit to exclude workflows (preserving original metadata)"
              GIT_AUTHOR_NAME="$ORIG_AUTHOR_NAME" \
              GIT_AUTHOR_EMAIL="$ORIG_AUTHOR_EMAIL" \
              GIT_AUTHOR_DATE="$ORIG_AUTHOR_DATE" \
              GIT_COMMITTER_NAME="$ORIG_COMMITTER_NAME" \
              GIT_COMMITTER_EMAIL="$ORIG_COMMITTER_EMAIL" \
              GIT_COMMITTER_DATE="$ORIG_COMMITTER_DATE" \
              git commit --amend --no-edit --no-gpg-sign
            else
              echo "No workflow files to remove"
            fi
          else
            echo "No .github/workflows directory found"
          fi

      - name: Push to public
        env:
          FORCE: ${{ github.event.inputs.force }}
        run: |
          set -euo pipefail
          
          if [ "${FORCE}" = "true" ]; then
            echo "⚠️ Force pushing to public (will overwrite history)"
            git push public temp-public-sync:main --force
            echo "✅ Force push completed"
          else
            REMOTE_SHA=$(git rev-parse public/main 2>/dev/null || echo "")
            LOCAL_SHA=$(git rev-parse temp-public-sync)
            
            if [ -z "$REMOTE_SHA" ]; then
              echo "Creating public main (first push)"
              git push public temp-public-sync:main
              echo "✅ Public repository initialized"
            elif [ "$REMOTE_SHA" = "$LOCAL_SHA" ]; then
              echo "✅ Public is already up to date"
            elif git merge-base --is-ancestor public/main temp-public-sync 2>/dev/null; then
              echo "Fast-forwarding public to match private"
              git push public temp-public-sync:main
              echo "✅ Successfully synced to public"
            else
              echo "❌ ERROR: Histories diverged. Public has changes not in private."
              echo "  Private SHA: $LOCAL_SHA"
              echo "  Public SHA:  $REMOTE_SHA"
              echo "  Run 'Pull from public' first, or manually trigger with force=true"
              exit 1
            fi
          fi

      - name: Cleanup
        if: always()
        run: |
          set +e  # Don't fail on cleanup errors
          git checkout main 2>/dev/null || true
          git branch -D temp-public-sync 2>/dev/null || true
          echo "Cleanup completed"

      - name: Push tags
        run: |
          set -euo pipefail
          mapfile -t TAGS < <(git tag -l 'v*' 'release/*' | sort -u)
          if [ "${#TAGS[@]}" -eq 0 ]; then
            echo "No release tags to push"
          else
            echo "Pushing ${#TAGS[@]} release tag(s)"
            for t in "${TAGS[@]}"; do
              echo "  Pushing tag: $t"
              git push public "refs/tags/${t}:refs/tags/${t}" --force || echo "  Failed to push $t"
            done
            echo "✅ Tags synced"
          fi
